create table if not exists public.audit_metrics (
    id text primary key default 'global_metrics',
    auth_events integer not null default 0,
    graph_writes integer not null default 0,
    overrides integer not null default 0,
    anomalies integer not null default 0,
    total_entries integer not null default 0,
    updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
    sequence bigint generated by default as identity primary key,
    hash text not null unique,
    timestamp timestamptz not null default now(),
    timezone_label text not null,
    actor_name text not null,
    actor_kind text not null, -- 'ai', 'system', 'user'
    actor_meta text not null,
    actor_badge text not null,
    action text not null,
    status_label text not null,
    outcome text not null, -- 'recorded', 'blocked', 'warning'
    anomaly boolean not null default false
);

create index if not exists idx_audit_logs_timestamp on public.audit_logs (timestamp desc);
create index if not exists idx_audit_logs_actor_kind on public.audit_logs (actor_kind);

-- Seed Metrics
insert into public.audit_metrics (id, auth_events, graph_writes, overrides, anomalies, total_entries)
values ('global_metrics', 14282, 842, 312, 12, 48291)
on conflict (id) do update set 
    auth_events = excluded.auth_events,
    graph_writes = excluded.graph_writes,
    overrides = excluded.overrides,
    anomalies = excluded.anomalies,
    total_entries = excluded.total_entries;

-- Seed Logs
insert into public.audit_logs (hash, timezone_label, actor_name, actor_kind, actor_meta, actor_badge, action, status_label, outcome, anomaly)
values
    ('0x8f9c...b12a', 'UTC-7', 'System Orchestrator', 'system', 'sys_admin_role', 'SO', 'Risk thresholds updated manually', 'Committed', 'recorded', false),
    ('0x4e2a...c981', 'UTC-3', 'Policy Graph v4.2', 'ai', 'neo4j_cluster', 'PG', 'Schema indices rebuilt', 'Optimized', 'recorded', false),
    ('0xa12f...d341', 'UTC-7', 'Sarah Chen', 'user', 'underwriter', 'SC', 'Elevated claim risk score', 'Approved', 'recorded', false),
    ('0xb981...11af', 'UTC-4', 'Anomaly Detector', 'ai', 'threat_model_v2', 'AD', 'Blocked unusual login pattern', 'Blocked', 'blocked', true),
    ('0xc782...88f1', 'UTC-7', 'API Gateway', 'system', 'us-east-1', 'API', 'Rate limit enforced on endpoint', 'Throttled', 'warning', true)
on conflict (hash) do nothing;
