"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

// Support English, Hindi, Tamil, Telugu, Kannada
export type Language = "en" | "hi" | "ta" | "te" | "kn";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        "nav.portal": "Portal",
        "nav.underwriter": "Underwriter",
        "nav.adjuster": "Adjuster",
        "nav.manager": "Manager",
        "nav.admin": "Admin",
        "nav.signin": "Sign In",
        
        "sidebar.home": "Overview",
        "sidebar.claims": "Claims History",
        "sidebar.submit": "File New Claim",
        "sidebar.policies": "Policy Vault",
        "sidebar.settings": "Security Settings",
        "sidebar.billing": "Billing & Payments",
        
        "dash.welcome": "Hello",
        "dash.title": "Customer Dashboard",
        "dash.active_policies": "Active Policies",
        "dash.view_all": "View all",
        "dash.total_coverage": "Total Coverage",
        "dash.premium_due": "Premium Due",
        "dash.recent_activity": "Recent Activity",
        "dash.smart_insight": "Smart Insight",
        "dash.gap_identified": "Gap Identified",
        "dash.learn_more": "Learn More",
        "dash.estimated_addon": "Estimated Add-on",
        "dash.status.active": "Active",
        "dash.status.review": "In Review",
        "dash.status.pending": "Pending Underwriting",

        "claims.title": "Claims History",
        "claims.subtitle": "A complete record of all your filed insurance claims and their outcomes.",
        "claims.status.review": "In Review",
        "claims.status.approved": "Approved",
        "claims.status.closed": "Closed",

        "billing.title": "Billing & Payments",
        "billing.subtitle": "Manage your payment methods, view invoices, and track premium schedules.",
        "billing.next_payment": "Next Payment",
        "billing.pay_now": "Pay Now",
        "billing.payment_method": "Payment Method",
        "billing.update_method": "Update Payment Method",
        "billing.history": "Payment History",
        "billing.status.paid": "Paid",

        "settings.title": "Security Settings",
        "settings.subtitle": "Manage your account security, privacy preferences, and notification settings.",
        "settings.password": "Password",
        "settings.password_desc": "Last changed 30 days ago",
        "settings.twofa": "Two-Factor Authentication",
        "settings.twofa_desc": "Enabled via Authenticator App",
        "settings.notifications": "Notification Preferences",
        "settings.notifications_desc": "Email & SMS alerts active",
        "settings.privacy": "Privacy Settings",
        "settings.privacy_desc": "Data sharing preferences",
        "settings.update": "Update",
        "settings.manage": "Manage",
        "settings.configure": "Configure",
        "settings.review": "Review",

        "policy.title": "My Policies",
        "policy.subtitle": "View your active insurance policies and coverage details.",
        "policy.monthly_premium": "Monthly Premium",
        "policy.coverage_details": "Coverage Details",
        "policy.coverage_item": "Coverage Item",
        "policy.limit": "Limit",
        "policy.deductible": "Deductible",

        "submit.title": "File New Claim",
        "submit.dashboard": "Dashboard",
        "submit.step_details": "Incident Details",
        "submit.step_evidence": "Evidence",
        "submit.step_review": "Review",
        "submit.incident_details": "Incident Details",
        "submit.incident_subtitle": "Tell us what happened with your protected asset.",
        "submit.claim_type": "Type of Claim",
        "submit.date_of_incident": "Date of Incident",
        "submit.approx_time": "Approx. Time",
        "submit.description": "Incident Description",
        "submit.evidence_title": "Supporting Evidence",
        "submit.evidence_subtitle": "Upload photos of the damage or relevant documents.",
        "submit.drag_drop": "Drag and drop files here",
        "submit.file_types": "PNG, JPG or PDF up to 10MB each",
        "submit.browse_files": "Browse Files",
        "submit.additional_evidence": "Additional Evidence",
        "submit.review_claim": "Review Claim",
        "submit.save_for_later": "Save for later",
        "submit.back": "Back",
        "submit.continue": "Continue",
        "submit.submit_claim": "Submit Claim",
        "submit.encrypted": "End-to-End Encrypted Secure Submission"
    },
    hi: {
        "nav.portal": "पोर्टल",
        "nav.underwriter": "अंडरराइटर",
        "nav.adjuster": "एडजस्टर",
        "nav.manager": "मैनेजर",
        "nav.admin": "व्यवस्थापक",
        "nav.signin": "साइन इन",
        
        "sidebar.home": "अवलोकन",
        "sidebar.claims": "दावों का इतिहास",
        "sidebar.submit": "नया दावा दर्ज करें",
        "sidebar.policies": "पॉलिसी वॉल्ट",
        "sidebar.settings": "सुरक्षा सेटिंग्स",
        "sidebar.billing": "बिलिंग और भुगतान",
        
        "dash.welcome": "नमस्ते",
        "dash.title": "ग्राहक डैशबोर्ड",
        "dash.active_policies": "सक्रिय पॉलिसी",
        "dash.view_all": "सभी देखें",
        "dash.total_coverage": "कुल कवरेज",
        "dash.premium_due": "प्रीमियम देय",
        "dash.recent_activity": "हाल की गतिविधि",
        "dash.smart_insight": "स्मार्ट इनसाइट",
        "dash.gap_identified": "कवरेज गैप",
        "dash.learn_more": "और जानें",
        "dash.estimated_addon": "अनुमानित लागत",
        "dash.status.active": "सक्रिय",
        "dash.status.review": "समीक्षा में",
        "dash.status.pending": "लंबित",

        "claims.title": "दावों का इतिहास",
        "claims.subtitle": "आपके सभी बीमा दावों और उनके परिणामों का पूरा रिकॉर्ड।",
        "claims.status.review": "समीक्षा में",
        "claims.status.approved": "स्वीकृत",
        "claims.status.closed": "बंद",

        "billing.title": "बिलिंग और भुगतान",
        "billing.subtitle": "अपनी भुगतान विधियों का प्रबंधन करें, चालान देखें और प्रीमियम ट्रैक करें।",
        "billing.next_payment": "अगला भुगतान",
        "billing.pay_now": "अभी भुगतान करें",
        "billing.payment_method": "भुगतान विधि",
        "billing.update_method": "भुगतान विधि अपडेट करें",
        "billing.history": "भुगतान इतिहास",
        "billing.status.paid": "भुगतान किया",

        "settings.title": "सुरक्षा सेटिंग्स",
        "settings.subtitle": "अपने खाते की सुरक्षा, गोपनीयता प्राथमिकताएं और सूचना सेटिंग्स प्रबंधित करें।",
        "settings.password": "पासवर्ड",
        "settings.password_desc": "30 दिन पहले बदला गया",
        "settings.twofa": "दो-कारक प्रमाणीकरण",
        "settings.twofa_desc": "ऑथेंटिकेटर ऐप सक्रिय",
        "settings.notifications": "सूचना प्राथमिकताएं",
        "settings.notifications_desc": "ईमेल और SMS अलर्ट सक्रिय",
        "settings.privacy": "गोपनीयता सेटिंग्स",
        "settings.privacy_desc": "डेटा साझाकरण प्राथमिकताएं",
        "settings.update": "अपडेट करें",
        "settings.manage": "प्रबंधित करें",
        "settings.configure": "कॉन्फ़िगर",
        "settings.review": "समीक्षा",

        "policy.title": "मेरी पॉलिसी",
        "policy.subtitle": "अपनी सक्रिय बीमा पॉलिसी और कवरेज विवरण देखें।",
        "policy.monthly_premium": "मासिक प्रीमियम",
        "policy.coverage_details": "कवरेज विवरण",
        "policy.coverage_item": "कवरेज मद",
        "policy.limit": "सीमा",
        "policy.deductible": "कटौती",

        "submit.title": "नया दावा दर्ज करें",
        "submit.dashboard": "डैशबोर्ड",
        "submit.step_details": "घटना विवरण",
        "submit.step_evidence": "प्रमाण",
        "submit.step_review": "समीक्षा",
        "submit.incident_details": "घटना विवरण",
        "submit.incident_subtitle": "अपनी सुरक्षित संपत्ति के साथ क्या हुआ बताएं।",
        "submit.claim_type": "दावे का प्रकार",
        "submit.date_of_incident": "घटना की तिथि",
        "submit.approx_time": "अनुमानित समय",
        "submit.description": "घटना विवरण",
        "submit.evidence_title": "सहायक प्रमाण",
        "submit.evidence_subtitle": "क्षति की तस्वीरें या संबंधित दस्तावेज़ अपलोड करें।",
        "submit.drag_drop": "फ़ाइलें यहां ड्रैग और ड्रॉप करें",
        "submit.file_types": "PNG, JPG या PDF 10MB तक",
        "submit.browse_files": "फ़ाइलें चुनें",
        "submit.additional_evidence": "अतिरिक्त प्रमाण",
        "submit.review_claim": "दावे की समीक्षा",
        "submit.save_for_later": "बाद के लिए सहेजें",
        "submit.back": "वापस",
        "submit.continue": "जारी रखें",
        "submit.submit_claim": "दावा जमा करें",
        "submit.encrypted": "एंड-टू-एंड एन्क्रिप्टेड सुरक्षित सबमिशन"
    },
    ta: {
        "nav.portal": "போர்டல்",
        "nav.underwriter": "அண்டர்ரைட்டர்",
        "nav.adjuster": "அட்ஜஸ்டர்",
        "nav.manager": "மேலாளர்",
        "nav.admin": "நிர்வாகி",
        "nav.signin": "உள்நுழை",
        
        "sidebar.home": "கண்ணோட்டம்",
        "sidebar.claims": "உரிமைகோரல் வரலாறு",
        "sidebar.submit": "புதிய உரிமைகோரல்",
        "sidebar.policies": "பாலிசி லாக்கர்",
        "sidebar.settings": "பாதுகாப்பு அமைப்புகள்",
        "sidebar.billing": "பில்லிங் & கட்டணம்",
        
        "dash.welcome": "வணக்கம்",
        "dash.title": "வாடிக்கையாளர் தளம்",
        "dash.active_policies": "செயலில் உள்ள பாலிசிகள்",
        "dash.view_all": "அனைத்தையும் காண்க",
        "dash.total_coverage": "மொத்த கவரேஜ்",
        "dash.premium_due": "பிரீமியம் நிலுவை",
        "dash.recent_activity": "சமீபத்திய செயல்கள்",
        "dash.smart_insight": "ஸ்மார்ட் தகவல்",
        "dash.gap_identified": "தேவை கண்டறியப்பட்டது",
        "dash.learn_more": "மேலும் அறிய",
        "dash.estimated_addon": "மதிப்பிடப்பட்ட செலவு",
        "dash.status.active": "செயலில்",
        "dash.status.review": "பரிசீலனையில்",
        "dash.status.pending": "நிலுவையில்",

        "claims.title": "உரிமைகோரல் வரலாறு",
        "claims.subtitle": "உங்கள் காப்பீட்டு உரிமைகோரல்கள் மற்றும் அவற்றின் முடிவுகளின் முழுமையான பதிவு.",
        "claims.status.review": "பரிசீலனையில்",
        "claims.status.approved": "ஒப்புதல்",
        "claims.status.closed": "மூடப்பட்டது",

        "billing.title": "பில்லிங் & கட்டணம்",
        "billing.subtitle": "உங்கள் கட்டண முறைகளை நிர்வகிக்கவும், ரசீதுகளைக் காணவும்.",
        "billing.next_payment": "அடுத்த கட்டணம்",
        "billing.pay_now": "இப்போது செலுத்து",
        "billing.payment_method": "கட்டண முறை",
        "billing.update_method": "முறை மாற்று",
        "billing.history": "கட்டண வரலாறு",
        "billing.status.paid": "செலுத்தப்பட்டது",

        "settings.title": "பாதுகாப்பு அமைப்புகள்",
        "settings.subtitle": "உங்கள் கணக்கு பாதுகாப்பு, தனியுரிமை விருப்பங்கள் மற்றும் அறிவிப்பு அமைப்புகளை நிர்வகிக்கவும்.",
        "settings.password": "கடவுச்சொல்",
        "settings.password_desc": "30 நாட்களுக்கு முன் மாற்றப்பட்டது",
        "settings.twofa": "இரு-காரணி அங்கீகாரம்",
        "settings.twofa_desc": "அங்கீகாரி ஆப் மூலம் செயல்படுத்தப்பட்டது",
        "settings.notifications": "அறிவிப்பு விருப்பங்கள்",
        "settings.notifications_desc": "மின்னஞ்சல் & SMS எச்சரிக்கைகள்",
        "settings.privacy": "தனியுரிமை அமைப்புகள்",
        "settings.privacy_desc": "தரவு பகிர்வு விருப்பங்கள்",
        "settings.update": "புதுப்பி",
        "settings.manage": "நிர்வகி",
        "settings.configure": "கட்டமை",
        "settings.review": "மதிப்பாய்வு",

        "policy.title": "எனது பாலிசிகள்",
        "policy.subtitle": "உங்கள் செயலில் உள்ள காப்பீட்டு பாலிசிகள் மற்றும் கவரேஜ் விவரங்கள்.",
        "policy.monthly_premium": "மாதாந்திர பிரீமியம்",
        "policy.coverage_details": "கவரேஜ் விவரங்கள்",
        "policy.coverage_item": "கவரேஜ் பொருள்",
        "policy.limit": "வரம்பு",
        "policy.deductible": "கழிவு",

        "submit.title": "புதிய உரிமைகோரல்",
        "submit.dashboard": "டாஷ்போர்டு",
        "submit.step_details": "நிகழ்வு விவரம்",
        "submit.step_evidence": "ஆதாரம்",
        "submit.step_review": "மதிப்பாய்வு",
        "submit.incident_details": "நிகழ்வு விவரம்",
        "submit.incident_subtitle": "உங்கள் பாதுகாக்கப்பட்ட சொத்துடன் என்ன நடந்தது என்பதைத் தெரிவிக்கவும்.",
        "submit.claim_type": "உரிமைகோரல் வகை",
        "submit.date_of_incident": "நிகழ்வு தேதி",
        "submit.approx_time": "தோராய நேரம்",
        "submit.description": "நிகழ்வு விவரணை",
        "submit.evidence_title": "ஆதார ஆவணங்கள்",
        "submit.evidence_subtitle": "சேத புகைப்படங்கள் அல்லது ஆவணங்களை பதிவேற்றவும்.",
        "submit.drag_drop": "இங்கே இழுத்து விடுங்கள்",
        "submit.file_types": "PNG, JPG அல்லது PDF 10MB வரை",
        "submit.browse_files": "கோப்புகளை உலாவு",
        "submit.additional_evidence": "கூடுதல் ஆதாரம்",
        "submit.review_claim": "உரிமைகோரலை மதிப்பாய்வு செய்",
        "submit.save_for_later": "பின்னர் சேமி",
        "submit.back": "பின்",
        "submit.continue": "தொடர்",
        "submit.submit_claim": "உரிமைகோரலை சமர்ப்பி",
        "submit.encrypted": "முழு குறியாக்க பாதுகாப்பு சமர்ப்பிப்பு"
    },
    te: {
        "nav.portal": "పోర్టల్",
        "nav.underwriter": "అండర్రైటర్",
        "nav.adjuster": "అడ్జస్టర్",
        "nav.manager": "మేనేజర్",
        "nav.admin": "అడ్మిన్",
        "nav.signin": "సైన్ ఇన్",
        
        "sidebar.home": "అవలోకనం",
        "sidebar.claims": "క్లెయిమ్ల చరిత్ర",
        "sidebar.submit": "కొత్త క్లెయిమ్",
        "sidebar.policies": "పాలసీ వాల్ట్",
        "sidebar.settings": "భద్రతా సెట్టింగ్‌లు",
        "sidebar.billing": "బిల్లింగ్ & చెల్లింపులు",
        
        "dash.welcome": "హలో",
        "dash.title": "కస్టమర్ డ్యాష్బోర్డ్",
        "dash.active_policies": "క్రియాశీల పాలసీలు",
        "dash.view_all": "అన్నీ వీక్షించండి",
        "dash.total_coverage": "మొత్తం కవరేజ్",
        "dash.premium_due": "ప్రీమియం గడువు",
        "dash.recent_activity": "తాజా కార్యాచరణ",
        "dash.smart_insight": "స్మార్ట్ అంతర్దృష్టి",
        "dash.gap_identified": "గ్యాప్ గుర్తించబడింది",
        "dash.learn_more": "మరింత తెలుసుకోండి",
        "dash.estimated_addon": "అంచనా వ్యయం",
        "dash.status.active": "చురుకైన",
        "dash.status.review": "సమీక్షలో ఉంది",
        "dash.status.pending": "పెండింగ్లో ఉంది",

        "claims.title": "క్లెయిమ్ల చరిత్ర",
        "claims.subtitle": "మీరు ఫైల్ చేసిన బీమా క్లెయిమ్‌ల పూర్తి రికార్డు.",
        "claims.status.review": "సమీక్షలో ఉంది",
        "claims.status.approved": "ఆమోదించబడింది",
        "claims.status.closed": "మూసివేయబడింది",

        "billing.title": "బిల్లింగ్ & చెల్లింపులు",
        "billing.subtitle": "చెల్లింపు పద్ధతులను నిర్వహించండి మరియు ఇన్వాయిస్‌లను వీక్షించండి.",
        "billing.next_payment": "తదుపరి చెల్లింపు",
        "billing.pay_now": "ఇప్పుడు కట్టు",
        "billing.payment_method": "చెల్లింపు పద్ధతి",
        "billing.update_method": "నవీకరించండి",
        "billing.history": "చెల్లింపు చరిత్ర",
        "billing.status.paid": "చెల్లించిన",

        "settings.title": "భద్రతా సెట్టింగ్‌లు",
        "settings.subtitle": "మీ ఖాతా భద్రత, గోప్యతా ప్రాధాన్యతలు మరియు నోటిఫికేషన్ సెట్టింగ్‌లను నిర్వహించండి.",
        "settings.password": "పాస్‌వర్డ్",
        "settings.password_desc": "30 రోజుల క్రితం మార్చబడింది",
        "settings.twofa": "రెండు-అంశ ధృవీకరణ",
        "settings.twofa_desc": "ఆథెంటికేటర్ యాప్ ద్వారా",
        "settings.notifications": "నోటిఫికేషన్ ప్రాధాన్యతలు",
        "settings.notifications_desc": "ఇమెయిల్ & SMS అలర్ట్‌లు సక్రియం",
        "settings.privacy": "గోప్యతా సెట్టింగ్‌లు",
        "settings.privacy_desc": "డేటా భాగస్వామ్య ప్రాధాన్యతలు",
        "settings.update": "నవీకరించు",
        "settings.manage": "నిర్వహించు",
        "settings.configure": "కాన్ఫిగర్",
        "settings.review": "సమీక్ష",

        "policy.title": "నా పాలసీలు",
        "policy.subtitle": "మీ సక్రియ బీమా పాలసీలు మరియు కవరేజ్ వివరాలను చూడండి.",
        "policy.monthly_premium": "నెలవారీ ప్రీమియం",
        "policy.coverage_details": "కవరేజ్ వివరాలు",
        "policy.coverage_item": "కవరేజ్ అంశం",
        "policy.limit": "పరిమితి",
        "policy.deductible": "మినహాయింపు",

        "submit.title": "కొత్త క్లెయిమ్ దాఖలు",
        "submit.dashboard": "డ్యాష్బోర్డ్",
        "submit.step_details": "సంఘటన వివరాలు",
        "submit.step_evidence": "ఆధారాలు",
        "submit.step_review": "సమీక్ష",
        "submit.incident_details": "సంఘటన వివరాలు",
        "submit.incident_subtitle": "మీ రక్షిత ఆస్తితో ఏమి జరిగిందో చెప్పండి.",
        "submit.claim_type": "క్లెయిమ్ రకం",
        "submit.date_of_incident": "సంఘటన తేదీ",
        "submit.approx_time": "సుమారు సమయం",
        "submit.description": "సంఘటన వివరణ",
        "submit.evidence_title": "ఆధార పత్రాలు",
        "submit.evidence_subtitle": "నష్టం ఫోటోలు లేదా పత్రాలను అప్‌లోడ్ చేయండి.",
        "submit.drag_drop": "ఫైళ్లను ఇక్కడ డ్రాగ్ చేయండి",
        "submit.file_types": "PNG, JPG లేదా PDF 10MB వరకు",
        "submit.browse_files": "ఫైళ్లు బ్రౌజ్ చేయండి",
        "submit.additional_evidence": "అదనపు ఆధారాలు",
        "submit.review_claim": "క్లెయిమ్ సమీక్ష",
        "submit.save_for_later": "తర్వాత సేవ్ చేయి",
        "submit.back": "వెనక్కి",
        "submit.continue": "కొనసాగించు",
        "submit.submit_claim": "క్లెయిమ్ సమర్పించు",
        "submit.encrypted": "ఎండ్-టు-ఎండ్ ఎన్క్రిప్టెడ్ సురక్షిత సమర్పణ"
    },
    kn: {
        "nav.portal": "ಪೋರ್ಟಲ್",
        "nav.underwriter": "ಅಂಡರ್ ರೈಟರ್",
        "nav.adjuster": "ಅಡ್ಜಸ್ಟರ್",
        "nav.manager": "ವ್ಯವಸ್ಥಾಪಕ",
        "nav.admin": "ನಿರ್ವಾಹಕ",
        "nav.signin": "ಸೈನ್ ಇನ್",
        
        "sidebar.home": "ಅವಲೋಕನ",
        "sidebar.claims": "ಕ್ಲೈಮ್ ಇತಿಹಾಸ",
        "sidebar.submit": "ಹೊಸ ಕ್ಲೈಮ್",
        "sidebar.policies": "ಪಾಲಿಸಿ ವಾಲ್ಟ್",
        "sidebar.settings": "ಭದ್ರತಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "sidebar.billing": "ಬಿಲ್ಲಿಂಗ್ ಮತ್ತು ಪಾವತಿ",
        
        "dash.welcome": "ನಮಸ್ಕಾರ",
        "dash.title": "ಗ್ರಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "dash.active_policies": "ಸಕ್ರಿಯ ಪಾಲಿಸಿಗಳು",
        "dash.view_all": "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
        "dash.total_coverage": "ಒಟ್ಟು ವ್ಯಾಪ್ತಿ",
        "dash.premium_due": "ಪ್ರೀಮಿಯಂ ಬಾಕಿ",
        "dash.recent_activity": "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
        "dash.smart_insight": "ಸ್ಮಾರ್ಟ್ ಒಳನೋಟ",
        "dash.gap_identified": "ಅಗತ್ಯ ಗುರುತಿಸಲಾಗಿದೆ",
        "dash.learn_more": "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",
        "dash.estimated_addon": "ಅಂದಾಜು ವೆಚ್ಚ",
        "dash.status.active": "ಸಕ್ರಿಯ",
        "dash.status.review": "ವಿಮರ್ಶೆಯಲ್ಲಿದೆ",
        "dash.status.pending": "ಬಾಕಿಯಿದೆ",

        "claims.title": "ಕ್ಲೈಮ್ ಇತಿಹಾಸ",
        "claims.subtitle": "ನಿಮ್ಮ ಎಲ್ಲಾ ವಿಮಾ ಕ್ಲೈಮ್‌ಗಳ ಸಂಪೂರ್ಣ ದಾಖಲೆ.",
        "claims.status.review": "ವಿಮರ್ಶೆಯಲ್ಲಿದೆ",
        "claims.status.approved": "ಅನುಮೋದಿಸಲಾಗಿದೆ",
        "claims.status.closed": "ಮುಚ್ಚಲಾಗಿದೆ",

        "billing.title": "ಬಿಲ್ಲಿಂಗ್ ಮತ್ತು ಪಾವತಿಗಳು",
        "billing.subtitle": "ನಿಮ್ಮ ಪಾವತಿ ವಿಧಾನಗಳನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ಇನ್‌ವಾಯ್ಸ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ.",
        "billing.next_payment": "ಮುಂದಿನ ಪಾವತಿ",
        "billing.pay_now": "ಈಗ ಪಾವತಿಸಿ",
        "billing.payment_method": "ಪಾವತಿ ವಿಧಾನ",
        "billing.update_method": "ನವೀಕರಿಸಿ",
        "billing.history": "ಪಾವತಿ ಇತಿಹಾಸ",
        "billing.status.paid": "ಪಾವತಿಸಲಾಗಿದೆ",

        "settings.title": "ಭದ್ರತಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "settings.subtitle": "ನಿಮ್ಮ ಖಾತೆ ಭದ್ರತೆ, ಗೌಪ್ಯತೆ ಆದ್ಯತೆಗಳು ಮತ್ತು ಅಧಿಸೂಚನೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
        "settings.password": "ಪಾಸ್‌ವರ್ಡ್",
        "settings.password_desc": "30 ದಿನಗಳ ಹಿಂದೆ ಬದಲಾಯಿಸಲಾಗಿದೆ",
        "settings.twofa": "ಎರಡು-ಅಂಶ ದೃಢೀಕರಣ",
        "settings.twofa_desc": "ಆಥೆಂಟಿಕೇಟರ್ ಆ್ಯಪ್ ಮೂಲಕ",
        "settings.notifications": "ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು",
        "settings.notifications_desc": "ಇಮೇಲ್ & SMS ಎಚ್ಚರಿಕೆಗಳು",
        "settings.privacy": "ಗೌಪ್ಯತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "settings.privacy_desc": "ಡೇಟಾ ಹಂಚಿಕೆ ಆದ್ಯತೆಗಳು",
        "settings.update": "ನವೀಕರಿಸು",
        "settings.manage": "ನಿರ್ವಹಿಸು",
        "settings.configure": "ಕಾನ್ಫಿಗರ್",
        "settings.review": "ಪರಿಶೀಲನೆ",

        "policy.title": "ನನ್ನ ಪಾಲಿಸಿಗಳು",
        "policy.subtitle": "ನಿಮ್ಮ ಸಕ್ರಿಯ ವಿಮಾ ಪಾಲಿಸಿಗಳು ಮತ್ತು ವ್ಯಾಪ್ತಿ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ.",
        "policy.monthly_premium": "ಮಾಸಿಕ ಪ್ರೀಮಿಯಂ",
        "policy.coverage_details": "ವ್ಯಾಪ್ತಿ ವಿವರಗಳು",
        "policy.coverage_item": "ವ್ಯಾಪ್ತಿ ಐಟಂ",
        "policy.limit": "ಮಿತಿ",
        "policy.deductible": "ಮಿನಹಾಯಿ",

        "submit.title": "ಹೊಸ ಕ್ಲೈಮ್ ಸಲ್ಲಿಸಿ",
        "submit.dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "submit.step_details": "ಘಟನೆ ವಿವರ",
        "submit.step_evidence": "ಪುರಾವೆ",
        "submit.step_review": "ಪರಿಶೀಲನೆ",
        "submit.incident_details": "ಘಟನೆ ವಿವರ",
        "submit.incident_subtitle": "ನಿಮ್ಮ ರಕ್ಷಿತ ಆಸ್ತಿಯೊಂದಿಗೆ ಏನಾಯಿತು ಎಂದು ತಿಳಿಸಿ.",
        "submit.claim_type": "ಕ್ಲೈಮ್ ಪ್ರಕಾರ",
        "submit.date_of_incident": "ಘಟನೆ ದಿನಾಂಕ",
        "submit.approx_time": "ಅಂದಾಜು ಸಮಯ",
        "submit.description": "ಘಟನೆ ವಿವರಣೆ",
        "submit.evidence_title": "ಪುರಾವೆ ದಾಖಲೆಗಳು",
        "submit.evidence_subtitle": "ಹಾನಿ ಫೋಟೋಗಳು ಅಥವಾ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        "submit.drag_drop": "ಇಲ್ಲಿ ಡ್ರ್ಯಾಗ್ ಮಾಡಿ",
        "submit.file_types": "PNG, JPG ಅಥವಾ PDF 10MB ವರೆಗೆ",
        "submit.browse_files": "ಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
        "submit.additional_evidence": "ಹೆಚ್ಚುವರಿ ಪುರಾವೆ",
        "submit.review_claim": "ಕ್ಲೈಮ್ ಪರಿಶೀಲನೆ",
        "submit.save_for_later": "ನಂತರ ಉಳಿಸಿ",
        "submit.back": "ಹಿಂದೆ",
        "submit.continue": "ಮುಂದುವರಿಸಿ",
        "submit.submit_claim": "ಕ್ಲೈಮ್ ಸಲ್ಲಿಸಿ",
        "submit.encrypted": "ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್‌ಕ್ರಿಪ್ಟೆಡ್ ಸುರಕ್ಷಿತ ಸಲ್ಲಿಕೆ"
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("en");

    // Persist language to localStorage
    useEffect(() => {
        const stored = localStorage.getItem("insurai_lang") as Language;
        if (stored && Object.keys(translations).includes(stored)) {
            setLanguage(stored);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem("insurai_lang", lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
